name: Deploy to AWS S3
run-name: ${{ github.actor }} is deploying ${{ github.sha }}
on:
  workflow_dispatch: ~
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_SESSION_NAME: ${{ vars.AWS_ROLE_SESSION_NAME }}
  AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}
  BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy Dist files to s3
        run: |
          cd ./dist
          aws s3 cp . s3://${{ env.BUCKET_NAME }}/ --recursive
